package main

import (
	"log"
	"net/http"

	"github.com/go-chi/chi/v5"
	_ "github.com/venosm/http-swagger/example/openapi3-go-chi/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/venosm/http-swagger"
)

// @title OpenAPI 3.0 Example API
// @version 1.0.0
// @description This is a sample server demonstrating OpenAPI 3.0 support.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v3
func main() {
	r := chi.NewRouter()

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/openapi.json"), // The url pointing to API definition
		httpSwagger.TryItOutEnabled(true),                            // Enable "Try it out" for OpenAPI 3.0
		httpSwagger.DefaultModelsExpandDepth(1),
		httpSwagger.ShowExtensions(true),
	))

	log.Println("Server starting on :1323")
	log.Fatal(http.ListenAndServe(":1323", r))
}